apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: streamlit
        image: charliwar/streamlit:1.0
        ports:
        - containerPort : 8501
        env:
        - name : REPOSITORY
          value : "https://github.com/charliwardbd/streamlit-demo1.git"