apiVersion: v1
kind: Service
metadata:
  name: streamlit-svc
  labels:
    env: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8080          # port exposed outside ClusterIP
    targetPort: 8501    # port exposed by Pod
  selector:
    env: dev