apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
       - http:
            paths:
            - path: /demo1
              backend:
                    serviceName: streamlit-demo1-svc
                    servicePort: 80
            - path: /demo2
              backend:
                    serviceName: streamlit-demo2-svc
                    servicePort: 80